/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockUploadedResponse {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl BlockUploadedResponse {
    pub fn new(hash: String, message: String) -> BlockUploadedResponse {
        BlockUploadedResponse {
            hash,
            message,
        }
    }
}

