/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Block {
    #[serde(rename = "data")]
    pub data: std::path::PathBuf,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "index")]
    pub index: i64,
    #[serde(rename = "size")]
    pub size: i32,
}

impl Block {
    pub fn new(data: std::path::PathBuf, hash: String, index: i64, size: i32) -> Block {
        Block {
            data,
            hash,
            index,
            size,
        }
    }
}

