/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirLister {
    #[serde(rename = "files")]
    pub files: Vec<models::FileInfo>,
}

impl DirLister {
    pub fn new(files: Vec<models::FileInfo>) -> DirLister {
        DirLister {
            files,
        }
    }
}

