/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirListTemplate {
    #[serde(rename = "cur_path")]
    pub cur_path: String,
    #[serde(rename = "lister")]
    pub lister: Box<models::DirLister>,
}

impl DirListTemplate {
    pub fn new(cur_path: String, lister: models::DirLister) -> DirListTemplate {
        DirListTemplate {
            cur_path,
            lister: Box::new(lister),
        }
    }
}

