/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorTemplate {
    #[serde(rename = "cur_path")]
    pub cur_path: String,
    #[serde(rename = "err")]
    pub err: Box<models::TemplateErr>,
    #[serde(rename = "message")]
    pub message: String,
}

impl ErrorTemplate {
    pub fn new(cur_path: String, err: models::TemplateErr, message: String) -> ErrorTemplate {
        ErrorTemplate {
            cur_path,
            err: Box::new(err),
            message,
        }
    }
}

