/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileInfo {
    #[serde(rename = "is_file")]
    pub is_file: bool,
    #[serde(rename = "last_modified")]
    pub last_modified: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path_uri")]
    pub path_uri: String,
    #[serde(rename = "progress")]
    pub progress: f32,
    #[serde(rename = "size")]
    pub size: i64,
}

impl FileInfo {
    pub fn new(is_file: bool, last_modified: i64, name: String, path_uri: String, progress: f32, size: i64) -> FileInfo {
        FileInfo {
            is_file,
            last_modified,
            name,
            path_uri,
            progress,
            size,
        }
    }
}

