/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct File {
    #[serde(rename = "file_content")]
    pub file_content: std::path::PathBuf,
    #[serde(rename = "file_hash")]
    pub file_hash: String,
}

impl File {
    pub fn new(file_content: std::path::PathBuf, file_hash: String) -> File {
        File {
            file_content,
            file_hash,
        }
    }
}

