/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileDownloadRequest : Request for file download with custom filename
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileDownloadRequest {
    /// The custom filename to use for download
    #[serde(rename = "file_name")]
    pub file_name: String,
}

impl FileDownloadRequest {
    /// Request for file download with custom filename
    pub fn new(file_name: String) -> FileDownloadRequest {
        FileDownloadRequest {
            file_name,
        }
    }
}

