/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileUploadResponse : Response for file upload
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileUploadResponse {
    /// The file hash
    #[serde(rename = "file_hash")]
    pub file_hash: String,
    /// Message indicating success
    #[serde(rename = "message")]
    pub message: String,
}

impl FileUploadResponse {
    /// Response for file upload
    pub fn new(file_hash: String, message: String) -> FileUploadResponse {
        FileUploadResponse {
            file_hash,
            message,
        }
    }
}

