/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlistStateResponse {
    #[serde(rename = "flist_state")]
    pub flist_state: Box<models::FlistState>,
}

impl FlistStateResponse {
    pub fn new(flist_state: models::FlistState) -> FlistStateResponse {
        FlistStateResponse {
            flist_state: Box::new(flist_state),
        }
    }
}

