/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlistStateInfo {
    #[serde(rename = "msg")]
    pub msg: String,
    #[serde(rename = "progress")]
    pub progress: f32,
}

impl FlistStateInfo {
    pub fn new(msg: String, progress: f32) -> FlistStateInfo {
        FlistStateInfo {
            msg,
            progress,
        }
    }
}

