/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlistStateInProgress {
    #[serde(rename = "InProgress")]
    pub in_progress: Box<models::FlistStateInfo>,
}

impl FlistStateInProgress {
    pub fn new(in_progress: models::FlistStateInfo) -> FlistStateInProgress {
        FlistStateInProgress {
            in_progress: Box::new(in_progress),
        }
    }
}

