/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlistStateCreated {
    #[serde(rename = "Created")]
    pub created: String,
}

impl FlistStateCreated {
    pub fn new(created: String) -> FlistStateCreated {
        FlistStateCreated {
            created,
        }
    }
}

