/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FlistState {
    FlistStateAccepted(Box<models::FlistStateAccepted>),
    FlistStateStarted(Box<models::FlistStateStarted>),
    FlistStateInProgress(Box<models::FlistStateInProgress>),
    FlistStateCreated(Box<models::FlistStateCreated>),
    FlistStateFailed(String),
}

impl Default for FlistState {
    fn default() -> Self {
        Self::FlistStateAccepted(Default::default())
    }
}

