/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListBlocksResponse : Response for listing blocks
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBlocksResponse {
    /// List of block hashes
    #[serde(rename = "blocks")]
    pub blocks: Vec<String>,
    /// Current page number
    #[serde(rename = "page")]
    pub page: i32,
    /// Number of items per page
    #[serde(rename = "per_page")]
    pub per_page: i32,
    /// Total number of blocks
    #[serde(rename = "total")]
    pub total: i64,
}

impl ListBlocksResponse {
    /// Response for listing blocks
    pub fn new(blocks: Vec<String>, page: i32, per_page: i32, total: i64) -> ListBlocksResponse {
        ListBlocksResponse {
            blocks,
            page,
            per_page,
            total,
        }
    }
}

