/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListBlocksParams : Query parameters for listing blocks
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBlocksParams {
    /// Page number (1-indexed)
    #[serde(rename = "page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub page: Option<Option<i32>>,
    /// Number of items per page
    #[serde(rename = "per_page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub per_page: Option<Option<i32>>,
}

impl ListBlocksParams {
    /// Query parameters for listing blocks
    pub fn new() -> ListBlocksParams {
        ListBlocksParams {
            page: None,
            per_page: None,
        }
    }
}

