/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviewResponse {
    #[serde(rename = "checksum")]
    pub checksum: String,
    #[serde(rename = "content")]
    pub content: Vec<String>,
    #[serde(rename = "metadata")]
    pub metadata: String,
}

impl PreviewResponse {
    pub fn new(checksum: String, content: Vec<String>, metadata: String) -> PreviewResponse {
        PreviewResponse {
            checksum,
            content,
            metadata,
        }
    }
}

