/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ResponseError {
    ResponseErrorInternalServerError(String),
    ResponseErrorConflict(Box<models::ResponseErrorConflict>),
    ResponseErrorNotFound(Box<models::ResponseErrorNotFound>),
    ResponseErrorUnauthorized(Box<models::ResponseErrorUnauthorized>),
    ResponseErrorBadRequest(Box<models::ResponseErrorBadRequest>),
    ResponseErrorForbidden(Box<models::ResponseErrorForbidden>),
    ResponseErrorTemplateError(Box<models::ResponseErrorTemplateError>),
}

impl Default for ResponseError {
    fn default() -> Self {
        Self::ResponseErrorInternalServerError(Default::default())
    }
}

