/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseErrorTemplateError {
    #[serde(rename = "TemplateError")]
    pub template_error: Box<models::ErrorTemplate>,
}

impl ResponseErrorTemplateError {
    pub fn new(template_error: models::ErrorTemplate) -> ResponseErrorTemplateError {
        ResponseErrorTemplateError {
            template_error: Box::new(template_error),
        }
    }
}

