/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseErrorBadRequest {
    #[serde(rename = "BadRequest")]
    pub bad_request: String,
}

impl ResponseErrorBadRequest {
    pub fn new(bad_request: String) -> ResponseErrorBadRequest {
        ResponseErrorBadRequest {
            bad_request,
        }
    }
}

