/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemplateErrInternalServerError {
    #[serde(rename = "InternalServerError")]
    pub internal_server_error: String,
}

impl TemplateErrInternalServerError {
    pub fn new(internal_server_error: String) -> TemplateErrInternalServerError {
        TemplateErrInternalServerError {
            internal_server_error,
        }
    }
}

