/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TemplateErr {
    TemplateErrBadRequest(Box<models::TemplateErrBadRequest>),
    TemplateErrNotFound(Box<models::TemplateErrNotFound>),
    TemplateErrInternalServerError(Box<models::TemplateErrInternalServerError>),
}

impl Default for TemplateErr {
    fn default() -> Self {
        Self::TemplateErrBadRequest(Default::default())
    }
}

