/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadBlockParams : Query parameters for uploading a block
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadBlockParams {
    /// File hash associated with the block
    #[serde(rename = "file_hash")]
    pub file_hash: String,
    /// Block index within the file
    #[serde(rename = "idx")]
    pub idx: i64,
}

impl UploadBlockParams {
    /// Query parameters for uploading a block
    pub fn new(file_hash: String, idx: i64) -> UploadBlockParams {
        UploadBlockParams {
            file_hash,
            idx,
        }
    }
}

