/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserBlockInfo : Block information with hash and size
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserBlockInfo {
    /// Block hash
    #[serde(rename = "hash")]
    pub hash: String,
    /// Block size in bytes
    #[serde(rename = "size")]
    pub size: i64,
}

impl UserBlockInfo {
    /// Block information with hash and size
    pub fn new(hash: String, size: i64) -> UserBlockInfo {
        UserBlockInfo {
            hash,
            size,
        }
    }
}

