/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserBlocksResponse : Response for user blocks endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserBlocksResponse {
    /// Total number of all blocks
    #[serde(rename = "all_blocks")]
    pub all_blocks: i64,
    /// List of blocks with their indices
    #[serde(rename = "blocks")]
    pub blocks: Vec<models::BlockInfo>,
    /// Total number of blocks
    #[serde(rename = "total")]
    pub total: i64,
}

impl UserBlocksResponse {
    /// Response for user blocks endpoint
    pub fn new(all_blocks: i64, blocks: Vec<models::BlockInfo>, total: i64) -> UserBlocksResponse {
        UserBlocksResponse {
            all_blocks,
            blocks,
            total,
        }
    }
}

