/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyBlocksRequest {
    /// List of blocks to verify
    #[serde(rename = "blocks")]
    pub blocks: Vec<models::VerifyBlock>,
}

impl VerifyBlocksRequest {
    pub fn new(blocks: Vec<models::VerifyBlock>) -> VerifyBlocksRequest {
        VerifyBlocksRequest {
            blocks,
        }
    }
}

