/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerifyBlock : Request to verify if multiple blocks exist on the server
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyBlock {
    /// Block hash to verify
    #[serde(rename = "block_hash")]
    pub block_hash: String,
    /// Block index within the file
    #[serde(rename = "block_index")]
    pub block_index: i64,
    /// File hash associated with the block
    #[serde(rename = "file_hash")]
    pub file_hash: String,
}

impl VerifyBlock {
    /// Request to verify if multiple blocks exist on the server
    pub fn new(block_hash: String, block_index: i64, file_hash: String) -> VerifyBlock {
        VerifyBlock {
            block_hash,
            block_index,
            file_hash,
        }
    }
}

