/*
 * rfs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerifyBlocksResponse : Response with list of missing blocks
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyBlocksResponse {
    /// List of block hashes that are missing on the server
    #[serde(rename = "missing")]
    pub missing: Vec<String>,
}

impl VerifyBlocksResponse {
    /// Response with list of missing blocks
    pub fn new(missing: Vec<String>) -> VerifyBlocksResponse {
        VerifyBlocksResponse {
            missing,
        }
    }
}

